apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: entandocomponentbundles.entando.org
spec:
  group: entando.org
  version: v1
  names:
    kind: EntandoComponentBundle
    plural: entandocomponentbundles
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          properties:
            code:
              type: string
              minLength: 3
              maxLength: 255
              pattern: '^(([a-z0-9]+)[\-_]?)+$'
            title:
              type: string
            description:
              type: string
            author:
              type: object
              properties:
                name:
                  type: string
                  pattern: '([a-zA-Z]\s?)+'
                email:
                  type: string
                  format: email
            organization:
                type: string
                minLength: 3
                maxLength: 255
                pattern: '^(?:[a-z0-9]+[\-_\.]?)+$'
            images:
              type: array
              items:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
            thumbnail:
              type: string
              maxLength: 320000
            version:
              type: array
              items:
                type: object
                properties:
                  version:
                    type: string
                  integrity:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
